import { parseArgs } from "util";
import { homedir } from "os";
import { join } from "path";
import { writeFileSync, chmodSync } from "fs";
import {
  listSearches,
  updateSearch,
  findOpencodeBinary,
  findProjectRoot,
  getDataDir,
  ensureDir,
} from "../../core/index";

function getCronScript(): string {
  return join(getDataDir(), "run-scheduled.sh");
}

export async function scheduleCommand(args: string[]) {
  const subcommand = args[0];
  const subArgs = args.slice(1);

  switch (subcommand) {
    case "set":
      await setSchedule(subArgs);
      break;
    case "clear":
      await clearSchedule(subArgs);
      break;
    case "install":
      await installCron();
      break;
    case "list":
      await listScheduled();
      break;
    default:
      console.log(`
Usage: mkt schedule <subcommand>

Manage scheduled runs via cron.

Subcommands:
  set <slug> <cron>    Set a cron schedule for a search
  clear <slug>         Remove the schedule from a search
  install              Generate cron installation script
  list                 Show all scheduled searches

Examples:
  mkt schedule set speakers "0 9 * * *"   # daily at 9am
  mkt schedule list
  mkt schedule install
`);
  }
}

async function setSchedule(args: string[]) {
  const { positionals } = parseArgs({
    args,
    allowPositionals: true,
  });

  if (positionals.length < 2) {
    console.error("Usage: mkt schedule set <slug> <cron>");
    console.error('Example: mkt schedule set speakers "0 9 * * *"');
    process.exit(1);
  }

  const slug = positionals[0];
  const cron = positionals[1];

  const search = updateSearch(slug, { schedule: cron });
  console.log(`Schedule set for ${slug}: ${cron}`);
  console.log("\nTo activate, run: mkt schedule install");
}

async function clearSchedule(args: string[]) {
  const { positionals } = parseArgs({
    args,
    allowPositionals: true,
  });

  if (positionals.length < 1) {
    console.error("Usage: mkt schedule clear <slug>");
    process.exit(1);
  }

  const slug = positionals[0];
  updateSearch(slug, { schedule: undefined });
  console.log(`Schedule cleared for ${slug}`);
}

async function installCron() {
  const searches = listSearches().filter((s) => s.schedule);

  if (searches.length === 0) {
    console.log("No searches with schedules.");
    console.log('Set one: mkt schedule set <slug> "0 9 * * *"');
    return;
  }

  const projectRoot = findProjectRoot();
  const mktPath = join(projectRoot, "apps/marketplace-tracker/src/cli/index.ts");

  const dataDir = getDataDir();
  const CRON_SCRIPT = getCronScript();
  ensureDir(dataDir);

  const script = `#!/bin/bash
# Generated by mkt
# Runs all scheduled marketplace searches

set -e
export PATH="${join(homedir(), ".opencode/bin")}:${join(homedir(), ".bun/bin")}:$PATH"

LOG="${join(dataDir, "cron.log")}"
MKT="bun ${mktPath}"

echo "========================================" >> "$LOG"
echo "Starting scheduled run at $(date)" >> "$LOG"
echo "========================================" >> "$LOG"

# Run all searches
$MKT run --all 2>&1 | tee -a "$LOG"

# Wait for jobs to complete (check every 30 seconds, max 30 minutes)
MAX_WAIT=1800
WAITED=0
while [ $WAITED -lt $MAX_WAIT ]; do
  RUNNING=$($MKT jobs --json 2>/dev/null | grep -c '"status":"running"' || echo 0)
  if [ "$RUNNING" -eq 0 ]; then
    echo "All jobs completed" >> "$LOG"
    break
  fi
  echo "Waiting for $RUNNING job(s) to complete..." >> "$LOG"
  sleep 30
  WAITED=$((WAITED + 30))
done

# Sync to extract reports
echo "Syncing job statuses..." >> "$LOG"
$MKT sync 2>&1 | tee -a "$LOG"

echo "Scheduled run completed at $(date)" >> "$LOG"
echo "" >> "$LOG"
`;

  writeFileSync(CRON_SCRIPT, script);
  chmodSync(CRON_SCRIPT, 0o755);

  console.log(`Created: ${CRON_SCRIPT}`);
  console.log("");
  console.log("Add these lines to your crontab (crontab -e):");
  console.log("");

  // Group by schedule
  const bySchedule = new Map<string, string[]>();
  for (const s of searches) {
    if (!s.schedule) continue;
    const list = bySchedule.get(s.schedule) || [];
    list.push(s.slug);
    bySchedule.set(s.schedule, list);
  }

  for (const [cron, slugs] of bySchedule) {
    console.log(`# ${slugs.join(", ")}`);
    console.log(`${cron} ${CRON_SCRIPT}`);
    console.log("");
  }

  console.log("Note: Each run processes searches sequentially to avoid Chrome conflicts.");
}

async function listScheduled() {
  const searches = listSearches().filter((s) => s.schedule);

  if (searches.length === 0) {
    console.log("No searches with schedules.");
    return;
  }

  console.log("");
  console.log("SEARCH".padEnd(25) + "SCHEDULE");
  console.log("-".repeat(50));

  for (const s of searches) {
    console.log(s.slug.padEnd(25) + s.schedule);
  }

  console.log("");
  console.log(`Cron script: ${getCronScript()}`);
}
